use online_marketplace;

-- https://www.kaggle.com/ylchang/coffee-shop-sample-data-1113

INSERT INTO product (name,seller_id) VALUES ('Brazilian - Organic', 2);
INSERT INTO product (name,seller_id) VALUES ('Our Old Time Diner Blend', 1);
INSERT INTO product (name,seller_id) VALUES ('Espresso Roast', 2);
INSERT INTO product (name,seller_id) VALUES ('Primo Espresso Roast', 5);
INSERT INTO product (name,seller_id) VALUES ('Columbian Medium Roast', 2);
INSERT INTO product (name,seller_id) VALUES ('Ethiopia', 3);
INSERT INTO product (name,seller_id) VALUES ('Jamacian Coffee River', 2);
INSERT INTO product (name,seller_id) VALUES ('Civet Cat', 3);
INSERT INTO product (name,seller_id) VALUES ('Organic Decaf Blend', 0);
INSERT INTO product (name,seller_id) VALUES ('Guatemalan Sustainably Grown', 2);
INSERT INTO product (name,seller_id) VALUES ('Lemon Grass', 4);
INSERT INTO product (name,seller_id) VALUES ('Peppermint', 5);
INSERT INTO product (name,seller_id) VALUES ('English Breakfast', 5);
INSERT INTO product (name,seller_id) VALUES ('Earl Grey', 4);
INSERT INTO product (name,seller_id) VALUES ('Serenity Green Tea', 0);
INSERT INTO product (name,seller_id) VALUES ('Traditional Blend Chai', 5);
INSERT INTO product (name,seller_id) VALUES ('Morning Sunrise Chai', 0);
INSERT INTO product (name,seller_id) VALUES ('Spicy Eye Opener Chai', 4);
INSERT INTO product (name,seller_id) VALUES ('Dark chocolate', 1);
INSERT INTO product (name,seller_id) VALUES ('Sustainably Grown Organic', 4);
INSERT INTO product (name,seller_id) VALUES ('Chili Mayan', 4);
INSERT INTO product (name,seller_id) VALUES ('Our Old Time Diner Blend Sm', 0);
INSERT INTO product (name,seller_id) VALUES ('Our Old Time Diner Blend Rg', 2);
INSERT INTO product (name,seller_id) VALUES ('Our Old Time Diner Blend Lg', 3);
INSERT INTO product (name,seller_id) VALUES ('Brazilian Sm', 3);
INSERT INTO product (name,seller_id) VALUES ('Brazilian Rg', 2);
INSERT INTO product (name,seller_id) VALUES ('Brazilian Lg', 3);
INSERT INTO product (name,seller_id) VALUES ('Columbian Medium Roast Sm', 2);
INSERT INTO product (name,seller_id) VALUES ('Columbian Medium Roast Rg', 0);
INSERT INTO product (name,seller_id) VALUES ('Columbian Medium Roast Lg', 2);
INSERT INTO product (name,seller_id) VALUES ('Ethiopia Sm', 4);
INSERT INTO product (name,seller_id) VALUES ('Ethiopia Rg', 4);
INSERT INTO product (name,seller_id) VALUES ('Ethiopia Lg', 5);
INSERT INTO product (name,seller_id) VALUES ('Jamaican Coffee River Sm', 4);
INSERT INTO product (name,seller_id) VALUES ('Jamaican Coffee River Rg', 3);
INSERT INTO product (name,seller_id) VALUES ('Jamaican Coffee River Lg', 3);
INSERT INTO product (name,seller_id) VALUES ('Espresso shot', 4);
INSERT INTO product (name,seller_id) VALUES ('Latte', 4);
INSERT INTO product (name,seller_id) VALUES ('Latte Rg', 0);
INSERT INTO product (name,seller_id) VALUES ('Cappuccino', 5);
INSERT INTO product (name,seller_id) VALUES ('Cappuccino Lg', 0);
INSERT INTO product (name,seller_id) VALUES ('Lemon Grass Rg', 5);
INSERT INTO product (name,seller_id) VALUES ('Lemon Grass Lg', 5);
INSERT INTO product (name,seller_id) VALUES ('Peppermint Rg', 2);
INSERT INTO product (name,seller_id) VALUES ('Peppermint Lg', 1);
INSERT INTO product (name,seller_id) VALUES ('Serenity Green Tea Rg', 4);
INSERT INTO product (name,seller_id) VALUES ('Serenity Green Tea Lg', 5);
INSERT INTO product (name,seller_id) VALUES ('English Breakfast Rg', 1);
INSERT INTO product (name,seller_id) VALUES ('English Breakfast Lg', 4);
INSERT INTO product (name,seller_id) VALUES ('Earl Grey Rg', 2);
INSERT INTO product (name,seller_id) VALUES ('Earl Grey Lg', 5);
INSERT INTO product (name,seller_id) VALUES ('Traditional Blend Chai Rg', 3);
INSERT INTO product (name,seller_id) VALUES ('Traditional Blend Chai Lg', 5);
INSERT INTO product (name,seller_id) VALUES ('Morning Sunrise Chai Rg', 2);
INSERT INTO product (name,seller_id) VALUES ('Morning Sunrise Chai Lg', 3);
INSERT INTO product (name,seller_id) VALUES ('Spicy Eye Opener Chai Rg', 0);
INSERT INTO product (name,seller_id) VALUES ('Spicy Eye Opener Chai Lg', 1);
INSERT INTO product (name,seller_id) VALUES ('Dark chocolate Rg', 1);
INSERT INTO product (name,seller_id) VALUES ('Dark chocolate Lg', 3);
INSERT INTO product (name,seller_id) VALUES ('Sustainably Grown Organic Rg', 5);
INSERT INTO product (name,seller_id) VALUES ('Sustainably Grown Organic Lg', 2);
INSERT INTO product (name,seller_id) VALUES ('Snow Day Hot Chocolate', 3);
INSERT INTO product (name,seller_id) VALUES ('Carmel syrup', 0);
INSERT INTO product (name,seller_id) VALUES ('Hazelnut syrup', 2);
INSERT INTO product (name,seller_id) VALUES ('Sugar Free Vanilla syrup', 1);
INSERT INTO product (name,seller_id) VALUES ('Pumpkin Spice Latte', 0);
INSERT INTO product (name,seller_id) VALUES ('Pumpkin Spice Latte Lg', 3);
INSERT INTO product (name,seller_id) VALUES ('Happy Holidays hot chocolate', 2);
INSERT INTO product (name,seller_id) VALUES ('Croissant', 5);
INSERT INTO product (name,seller_id) VALUES ('Cranberry Scone', 5);
INSERT INTO product (name,seller_id) VALUES ('Chocolate Croissant', 2);
INSERT INTO product (name,seller_id) VALUES ('Ginger Scone', 0);
INSERT INTO product (name,seller_id) VALUES ('Almond Croissant', 5);
INSERT INTO product (name,seller_id) VALUES ('Ginger Biscotti', 3);
INSERT INTO product (name,seller_id) VALUES ('Hazelnut Biscotti', 0);
INSERT INTO product (name,seller_id) VALUES ('Chocolate Chip Biscotti', 5);
INSERT INTO product (name,seller_id) VALUES ('Oatmeal Scone', 5);
INSERT INTO product (name,seller_id) VALUES ('Scottish Cream Scone ', 5);
INSERT INTO product (name,seller_id) VALUES ('Jumbo Savory Scone', 3);
INSERT INTO product (name,seller_id) VALUES ('I Need My Bean! Toque', 5);
INSERT INTO product (name,seller_id) VALUES ('I Need My Bean! T-shirt', 3);
INSERT INTO product (name,seller_id) VALUES ('I Need My Bean! Diner mug', 3);
INSERT INTO product (name,seller_id) VALUES ('I Need My Bean! Latte cup', 1);
INSERT INTO product (name,seller_id) VALUES ('Chocolate syrup', 5);
INSERT INTO product (name,seller_id) VALUES ('Rio Nights', 4);
INSERT INTO product (name,seller_id) VALUES ('Ouro Brasileiro shot', 3);
INSERT INTO product (name,seller_id) VALUES ('Ouro Brasileiro shot promo', 2);
INSERT INTO product (name,seller_id) VALUES ('Ginger Scone promo', 1);
