spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_marketplace
    username: root
    password: root_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect